// api/voice.js — AI voice overview: ElevenLabs TTS with data-driven scripts
// Scripts generated by Claude when credits available; rich data-driven fallbacks otherwise.

const SHOW_CONFIG = {
  "rate-watch-daily":        { voice: "onwK4e9ZLuTAKqWW03F9", name: "Daniel"   },
  "the-fed-report":          { voice: "pqHfZKP75CvOlQylNhV4", name: "Bill"     },
  "housing-market-weekly":   { voice: "SAz9YHcvj6GT2YYXdXww", name: "River"    },
  "mortgage-news-now":       { voice: "cjVigY5qzO86Huf0OWal", name: "Eric"     },
  "credit-score-clinic":     { voice: "Xb7hH8MSUJpSbSDYk0k2", name: "Alice"    },
  "down-payment-decoded":    { voice: "ZT9u07TYPVl83ejeLakq", name: "Rachelle" },
  "the-affordability-index": { voice: "nPczCjzI2devNBz1zQrb", name: "Brian"    },
  "hmda-deep-dive":          { voice: "JBFqnCBsd6RMkjVDRZzb", name: "George"   },
};

const BUCKET = 'equity-audio';

// ── Math helpers ──────────────────────────────────────────────────
function r2(v, sfx='%'){ return v!=null ? v.toFixed(2)+sfx : null; }
function pmt(principal, rate){
  if(!principal||!rate) return null;
  var mr=rate/100/12, n=360;
  return Math.round(principal*(mr*Math.pow(1+mr,n))/(Math.pow(1+mr,n)-1));
}
function fmtDollar(n){ return n!=null ? '$'+Math.round(n).toLocaleString() : null; }
function incReq(price, rate){
  if(!price||!rate) return null;
  var mr=rate/100/12, n=360;
  return Math.round(price*0.80*(mr*Math.pow(1+mr,n))/(Math.pow(1+mr,n)-1)*12/0.28/1000);
}
function affPct(price, rate, inc){
  if(!price||!rate||!inc) return null;
  var mr=rate/100/12, n=360;
  return (price*0.80*(mr*Math.pow(1+mr,n))/(Math.pow(1+mr,n)-1)/(inc/12)*100).toFixed(1);
}

// ── Data-driven fallback scripts (~180 words each) ───────────────
function buildFallback(show, d) {
  var r30  = r2(d.r30);
  var r15  = r2(d.r15);
  var t10  = r2(d.t10);
  var t2   = r2(d.t2);
  var ff   = r2(d.ff);
  var sp   = d.r30&&d.t10 ? (d.r30-d.t10).toFixed(2)+'%' : null;
  var yc   = d.t10&&d.t2 ? (d.t10>d.t2 ? 'normal, with a '+(d.t10-d.t2).toFixed(2)+' percent spread between the 10-year and 2-year Treasury' : 'inverted by '+Math.abs(d.t10-d.t2).toFixed(2)+' percent') : 'shape indeterminate';
  var pr   = d.median_price ? '$'+Math.round(d.median_price/1000)+'K' : null;
  var sup  = d.months_supply ? d.months_supply.toFixed(1) : null;
  var cond = !d.months_supply ? 'mixed' : d.months_supply<3 ? 'a hot seller\'s market' : d.months_supply<5 ? 'a seller\'s market' : d.months_supply<7 ? 'balanced' : 'a buyer\'s market';
  var inc  = d.median_income ? '$'+Math.round(d.median_income/1000)+'K' : null;
  var pmt20= d.median_price&&d.r30 ? fmtDollar(pmt(d.median_price*0.80,d.r30)) : null;
  var pmt3 = d.median_price&&d.r30 ? fmtDollar(pmt(d.median_price*0.97,d.r30)) : null;
  var dp3  = d.median_price ? '$'+Math.round(d.median_price*0.03/1000)+'K' : null;
  var dp20 = d.median_price ? '$'+Math.round(d.median_price*0.20/1000)+'K' : null;
  var affR = affPct(d.median_price,d.r30,d.median_income);
  var iReq = incReq(d.median_price,d.r30) ? '$'+incReq(d.median_price,d.r30)+'K' : null;
  var cc   = d.cc_delinquency ? d.cc_delinquency.toFixed(2)+'%' : null;
  var md   = d.mortgage_delinquency ? d.mortgage_delinquency.toFixed(2)+'%' : null;
  var hs   = d.housing_starts ? Math.round(d.housing_starts)+'K' : null;
  var ns   = d.new_home_sales ? d.new_home_sales+'K' : null;
  var es   = d.existing_home_sales ? (d.existing_home_sales/1e6).toFixed(2)+'M' : null;
  var ib   = d.inflation_breakeven ? d.inflation_breakeven.toFixed(2)+'%' : null;
  var bs   = d.fed_balance_sheet ? '$'+(d.fed_balance_sheet/1e9).toFixed(0)+'B' : null;
  var p400 = d.r30 ? fmtDollar(pmt(400000,d.r30)) : null;
  var i400 = d.r30 ? '$'+Math.round(pmt(400000,d.r30)*12/0.28/1000)+'K' : null;

  const scripts = {
    "rate-watch-daily": `The ${r30||'current'} thirty-year fixed rate is the headline number driving every rate conversation in the mortgage industry today. The fifteen-year is sitting at ${r15||'lower levels'}, and the ten-year Treasury — the benchmark that mortgage rates shadow most closely — is at ${t10||'current levels'}. The mortgage-to-Treasury spread is ${sp||'elevated'}, meaning lenders are pricing in${sp&&parseFloat(sp)>2?' a historically wide risk premium — something that has historically compressed when bond market volatility eases, which could pull mortgage rates lower even without Fed action':' risk premium above the historical norm of around 175 basis points'}. The yield curve is ${yc}, and the Fed Funds rate sits at ${ff||'current levels'}. For your clients asking whether to lock or float — the spread compression story is real, and if the Fed signals rate cuts while the economy avoids a hard landing, there is a credible path to rates in the fives. Lock conservatively if they are closing in thirty days. Float with a plan if they have sixty days or more.`,

    "the-fed-report": `The Federal Reserve's current policy stance is one of deliberate patience — holding the Fed Funds rate at ${ff||'current levels'} while monitoring whether inflation is sustainably moving toward the two percent target. The ten-year Treasury is at ${t10||'current levels'} and the two-year is at ${t2||'current levels'}, giving us a yield curve that is ${yc}. The ten-year inflation breakeven — what the bond market expects inflation to average over the next decade — is at ${ib||'current levels'}, which tells us the market believes the Fed's inflation fight is largely working. The Fed's balance sheet stands at ${bs||'a substantial level'}, and quantitative tightening continues to remove liquidity from the system, keeping upward pressure on long-end yields. For mortgage professionals, the key question is timing: markets are pricing in rate cuts, but the Fed is in no rush. Rates in the fives are possible in the next twelve months — but only if inflation data cooperates and employment softens. Manage your clients' expectations accordingly.`,

    "housing-market-weekly": `The housing market is in ${cond} right now, with ${sup||'limited'} months of supply nationally. The median home price stands at ${pr||'elevated levels'}, supported by a persistent mismatch between buyer demand and available homes. Housing starts came in at ${hs||'recent'} thousand annualized units — still running well below the roughly one-point-five million units per year needed to close the structural housing deficit built up over the last decade. New home sales are tracking at ${ns||'recent'} thousand annualized, while existing home sales are running at ${es||'recent levels'} — reflecting the lock-in effect, where homeowners with sub-four-percent mortgages are reluctant to sell and take on today's rates. For a buyer, the story is this: prices are holding because supply is not coming. For a seller, the story is that your pricing power is real, but days on market are stretching as affordability bites. The thirty-year rate at ${r30||'current levels'} is the variable that matters most — any meaningful rate relief will unlock both supply and demand simultaneously.`,

    "mortgage-news-now": `The mortgage market is operating in an environment where the thirty-year fixed at ${r30||'current levels'} is suppressing refinance volume to near-historic lows while keeping purchase origination under sustained pressure. The fifteen-year is at ${r15||'current levels'}, and the ten-year Treasury at ${t10||'current levels'} — with a mortgage spread of ${sp||'above normal'} — signals that lenders are still pricing in meaningful credit and liquidity risk. On the consumer side, the credit card delinquency rate is ${cc||'elevated'} and mortgage delinquency sits at ${md||'current levels'}. Delinquency trends at these levels are not catastrophic, but they signal that household balance sheet stress is real, particularly for borrowers who stretched to buy in the last two years. For lenders, this means underwriting discipline matters more than it has in years. Watch the thirty-day delinquency roll rates — they are the earliest signal of tightening that is about to show up in overlays. For loan officers, cash-out refis for debt consolidation are the product that makes sense in this environment.`,

    "credit-score-clinic": `Credit score and debt-to-income are the two variables loan officers can actually move, and in today's rate environment, they matter more than ever. With the thirty-year fixed at ${r30||'current levels'}, the monthly principal and interest on a four-hundred-thousand-dollar loan is ${p400||'significant'} — which requires approximately ${i400||'substantial'} in annual income to qualify under a twenty-eight percent front-end debt-to-income ratio. The national credit card delinquency rate of ${cc||'elevated levels'} and mortgage delinquency at ${md||'current levels'} confirm that a meaningful portion of borrowers are under cash-flow pressure. For loan officers, the credit score tier between seven-twenty and seven-sixty is where the most pricing improvement lives — moving a borrower from seven-nineteen to seven-twenty-one can save them a quarter point in rate and thousands over the life of the loan. The two fastest ways to move the needle: pay down revolving balances below thirty percent utilization, and dispute any inaccurate derogatories before application. Done right, both can show results in thirty to forty-five days.`,

    "down-payment-decoded": `At the national median home price of ${pr||'current levels'}, the down payment decision is one of the most consequential choices a buyer will make. A three-percent conventional down payment means bringing ${dp3||'a smaller sum'} to the table with a monthly payment of ${pmt3||'a higher amount'} — which includes private mortgage insurance until you reach twenty percent equity. A twenty-percent down payment requires ${dp20||'a larger sum'} but delivers a payment of ${pmt20||'a lower amount'} with no PMI and immediate equity cushion. The math on PMI often surprises buyers — for many, paying PMI for three to five years while preserving liquid savings is the smarter financial decision, especially in a market where waiting to save twenty percent means chasing a rising price floor. For buyers who don't have the twenty percent, VA and USDA zero-down loans are underutilized gems — VA in particular has no PMI at all. And down payment assistance programs exist in virtually every state, many of which go unclaimed. The conversation about down payment is never just about the check — it is about liquidity, monthly cash flow, and long-term financial strategy.`,

    "the-affordability-index": `Housing affordability is the defining challenge of this real estate cycle, and the numbers tell a stark story. With the median home price at ${pr||'current levels'}, the thirty-year rate at ${r30||'current levels'}, and the national median household income at ${inc||'current levels'}, the monthly principal and interest payment at twenty percent down is ${pmt20||'significant'}. That payment represents ${affR||'an elevated'} percent of the median household's monthly gross income — well above the traditional twenty-eight percent qualifying guideline. To meet that guideline, a buyer needs ${iReq||'substantially more than the median'} in annual income. The supply picture — ${sup||'limited'} months — tells us price relief is not coming from inventory. For rates to close the affordability gap meaningfully, the thirty-year fixed would need to fall at least one to one-point-five full percentage points. That is a scenario the bond market is partially pricing in, contingent on Fed rate cuts. Until then, the buyers who are closing are either high-income earners, dual-income households, or buyers with equity from a previous home. The starter-home buyer is the most challenged cohort in a generation.`,

    "hmda-deep-dive": `The lending environment right now — a thirty-year rate of ${r30||'near six percent'}, mortgage delinquency at ${md||'current levels'}, and credit card delinquency at ${cc||'current levels'} — is one where market share is actively shifting between lenders, and the loan officers who understand their local data have a genuine competitive advantage. The Huit AI APEX platform holds seven years of HMDA federal data — fourteen-point-two million loan records — covering approval and denial rates, lender market share, origination mix, rate spread analysis, and demographic lending patterns, broken down by county, lender, and loan type. In an elevated-rate environment like this one, the origination mix tilts toward purchase and government-backed loans — FHA, VA, and USDA — while conventional refinance volume contracts sharply. HMDA data shows which lenders are gaining purchase market share, where denial rates are climbing due to DTI stress, and which geographies are defying the national trend with stronger volume. For a loan officer or branch manager, that intelligence is the difference between chasing leads and knowing exactly where to prospect. The APEX platform makes that analysis available in minutes.`
  };

  return scripts[show] || `Welcome to The Equity Network. Today's live market data shows the thirty-year fixed rate at ${r30||'current levels'}, with a median home price of ${pr||'current levels'} nationally. Stay tuned for comprehensive mortgage and housing intelligence, powered by Huit dot A I.`;
}

// ── Claude script generation (when credits available) ────────────
async function generateScript(show, fred) {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) throw new Error('No key');

  const helpers = { r2, pmt, fmtDollar, incReq, affPct };
  // Use the fallback as a base but ask Claude to enrich with its own language
  const base = buildFallback(show, fred);

  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method:'POST',
    headers:{'Content-Type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01'},
    body:JSON.stringify({
      model:'claude-haiku-4-5-20251001',
      max_tokens:800,
      system:'You are a professional broadcast host. Rewrite the provided script in your own voice — keep all the data points and structure, but make the language more natural and conversational for broadcast. Output ONLY the rewritten script as one paragraph. Do not add labels, stage directions, or explanation. Hit exactly 180 words.',
      messages:[{role:'user',content:`Rewrite this broadcast script for the show "${show}" in a natural broadcast voice. Keep every data point. Hit exactly 180 words.\n\n${base}`}]
    })
  });
  if (!res.ok) throw new Error('Claude '+res.status);
  const data = await res.json();
  return data.content?.filter(b=>b.type==='text').map(b=>b.text).join('').trim();
}

// ── ElevenLabs TTS ────────────────────────────────────────────────
async function generateAudio(script, voiceId, elKey) {
  const res = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`, {
    method:'POST',
    headers:{'xi-api-key':elKey,'Content-Type':'application/json','Accept':'audio/mpeg'},
    body:JSON.stringify({
      text:script,
      model_id:'eleven_turbo_v2_5',
      voice_settings:{stability:0.45,similarity_boost:0.80,style:0.25,use_speaker_boost:true}
    })
  });
  if (!res.ok) throw new Error('ElevenLabs '+res.status+': '+(await res.text()).slice(0,200));
  return Buffer.from(await res.arrayBuffer());
}

// ── Supabase cache ────────────────────────────────────────────────
async function checkCache(show, sbUrl, sbKey) {
  const today = new Date().toISOString().slice(0,10).replace(/-/g,'');
  const res = await fetch(`${sbUrl}/storage/v1/object/info/${BUCKET}/${show}/${today}.mp3`,
    {headers:{'Authorization':'Bearer '+sbKey}});
  if (res.ok) return `${sbUrl}/storage/v1/object/public/${BUCKET}/${show}/${today}.mp3`;
  return null;
}
async function uploadCache(show, buf, sbUrl, sbKey) {
  const today = new Date().toISOString().slice(0,10).replace(/-/g,'');
  const res = await fetch(`${sbUrl}/storage/v1/object/${BUCKET}/${show}/${today}.mp3`, {
    method:'POST',
    headers:{'Authorization':'Bearer '+sbKey,'Content-Type':'audio/mpeg','x-upsert':'true'},
    body:buf
  });
  if (!res.ok) throw new Error('Supabase '+res.status);
  return `${sbUrl}/storage/v1/object/public/${BUCKET}/${show}/${today}.mp3`;
}

// ── FRED data ─────────────────────────────────────────────────────
async function getFred(show, host) {
  try {
    const r = await fetch(`https://${host}/api/fred?show=${show}`);
    if (r.ok) return await r.json();
  } catch(e) {}
  return {};
}

// ── Handler ───────────────────────────────────────────────────────
export default async function handler(req, res) {
  const show = req.query.show;
  if (!show || !SHOW_CONFIG[show])
    return res.status(400).json({error:'Invalid show: '+show});

  const cfg    = SHOW_CONFIG[show];
  const EL_KEY = process.env.ELEVENLABS_API_KEY;
  const SB_URL = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
  const SB_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  res.setHeader('Access-Control-Allow-Origin','*');

  // Check Supabase cache first
  if (SB_URL && SB_KEY) {
    try {
      const cached = await checkCache(show, SB_URL, SB_KEY);
      if (cached) return res.status(200).json({audioUrl:cached, show, voice:cfg.name, cached:true});
    } catch(e) { console.warn('Cache check:',e.message); }
  }

  // Fetch live FRED data
  const fred = await getFred(show, req.headers.host);

  // Try Claude first; fall back to data-driven script if unavailable
  let script;
  try {
    script = await generateScript(show, fred);
    console.log(`[voice] Claude script: ${script.split(' ').length}w`);
  } catch(e) {
    console.warn('[voice] Claude unavailable, using data-driven script:', e.message);
    script = buildFallback(show, fred);
    console.log(`[voice] Fallback script: ${script.split(' ').length}w`);
  }

  if (!EL_KEY) return res.status(500).json({error:'No ElevenLabs key', script});

  // Generate audio
  let buf;
  try {
    buf = await generateAudio(script, cfg.voice, EL_KEY);
  } catch(e) {
    return res.status(500).json({error:'TTS failed: '+e.message, script});
  }

  // Upload to Supabase cache
  if (SB_URL && SB_KEY) {
    try {
      const url = await uploadCache(show, buf, SB_URL, SB_KEY);
      return res.status(200).json({audioUrl:url, show, voice:cfg.name, script, cached:false});
    } catch(e) { console.warn('Supabase upload:',e.message); }
  }

  // Serve binary directly
  res.setHeader('Content-Type','audio/mpeg');
  res.setHeader('Content-Length',buf.length);
  res.setHeader('Cache-Control','s-maxage=86400');
  return res.status(200).send(buf);
}
